.github/workflows/azure-static-web-app-kind-mushroom-03c272603.yml
.storybook/main.ts
package.json
src/main.ts
src/styles/global.css
src/styles/imports.css

Lagt til en yml script til å lage en azure static app som skal hoste test storybook applikasjoner når man lager en PR.
I .storybook/main.ts måtte jeg reorganisere ting lit. Storybook bundler alle static filer når de importeres i storybook/main.ts men da jeg prøvde med vår css med variabler den klaga at den ikke skjønte :root syntaksen. Derfor måtte jeg bruke previewHead til det. Storybook skjønte ikke heller import i css files derfor må jeg importere fonter og shoelace styles via cdn.  Måtte også endre pathen til css filer før og etter bygg. 
Jeg vet ikke om vi skal fortsatt bruke copy-files derfor lagde jeg en separat npm script copy-files-storybook som kopierer css filer til storybook bygg mappe. 
Siden vi ikke trenger (og kan) importere css filer i andre css filer, splitta jeg …

PR: avn-253 test storybook app on pr

---

README.md
doc/components.md
doc/nve-button.md
doc/nve-icon.md
doc/nve-spinner.md
package-lock.json
package.json
src/components/nve-button/nve-button.ts
src/components/nve-icon/nve-icon.ts
src/components/nve-spinner/nve-spinner.ts

Her er mitt forslag til dokumentasjonsopplegg i tillegg til Storybook.
Tanken er å dokumentere med [JsDoc-tags](https://github.com/runem/web-component-analyzer#-how-to-document-your-components-using-jsdoc) i koden, slik vi er vant til, og slik Shoelace gjør det. Da blir dokumentasjonen også tilgjengelig for utviklere i VS Code.
Utfra dette [genererer vi markdown-filer](https://github.com/runem/web-component-analyzer) som legges i en egen mappe i Github. [Slik ser det ut](https://github.com/NVE/Designsystem/blob/task/avn-255-documentation-guidelines/doc/components.md).
Det er kun det vi lager selv som trenger å dokumenteres. Om du extender en Shoelace-komponent, blir all dokumentasjon fra Shoelace også med.
Se også forslag til veiledning til dokumentasjon i Readme.
Jeg har laget forslag …

AVN-255: Forslag til opplegg og støtte til dokumentasjon

---

.storybook/main.ts
doc/components.md
doc/nve-button.md
doc/nve-input.md
doc/nve-label.md
doc/nve-tooltip.md
index.html
src/components/index.ts
src/components/nve-button/nve-button-demo.ts
src/components/nve-icon/nve-icon.ts
src/components/nve-input/nve-input-demo.ts
src/components/nve-input/nve-input.styles.ts
src/components/nve-input/nve-input.ts
src/components/nve-label/nve-label-demo.ts
src/components/nve-label/nve-label.styles.ts
src/components/nve-label/nve-label.ts
src/components/nve-tooltip/nve-tooltip-demo.ts
src/components/nve-tooltip/nve-tooltip.ts
src/main.ts
src/stories/NveButton.stories.ts
src/stories/NveInput.stories.ts
src/stories/NveInput.ts
src/stories/NveLabel.stories.ts
src/stories/NveLabel.ts
src/styles/testsite.css
src/utils/slot.ts

Da er nve-input klar til slakt.
Med på kjøpet får du også nve-label og nve-tooltip, siden nve-input trenger begge disse.
nve-tooltip har ingen nve-styling ennå da den ikke er ferdig i Figma. Jeg har heller ikke laget storybook for denne.
Takk til @Citaborg for god hjelp!
Jeg har rappet test-opplegget til Lars Thomas i #17. Synes dette er lett å jobbe med når man utvikler komponenter, og jeg tror det gir en bra demo for utviklere som skal bruke komponentene også, når vi får til å publisere test-appen. 
Ellers er det "bare" å kjøre `npm run dev` og åpne testsida i en nettleser  for dem som har utviklingsmiljø.
For å vise slot-innhold i tooltip (slik at vi kan vise noe annet enn ren tekst), har jeg "lånt" en klasse fra Shoelace og modifisert denne litt. Vi må gjerne diskutere hvordan vi kan …

AVN-223: nve-input

---

tokens/public/device/base.json

(som også ligger i shoelace token)

Lagt til token: borderRadius-circle og borderRadius-pill 

---

src/components/nve-input/nve-input.styles.ts
src/components/nve-label/nve-label-demo.ts
src/components/nve-label/nve-label.styles.ts
src/components/nve-label/nve-label.ts

Diverse småfiks:
- Label må importere nve-tooltip og nve-icon siden den bruker dette internt
- Label hadde feil farge
- Label kan nå også vise innhold som ligger i standard-slot
- Skrivebeskytta input skal også ha runde hjørner selv om ramma ikke er synlig

Fiks av farge, runde hjørner og imports på nve-label og nve-input

---

.gitattributes
doc/.gitattributes

API-dokumentasjonen får automatisk kun LF som linjeskift, i motsetning til de fleste andre tekstfiler i Windows, som får CR+LF som linjeskift.
I Github lagres alle tekstfiler kun med LF som linjeskift, men Git-klienten på Windows bytter ut alle LF med CR+LF. Dette kalles LF-normalisering. 
Men scriptet som genererer API-dok-filene lagrer filene med kun LF som linjeskift, derfor tror Git at alle api-dok-filer er endret hver gang man genererer dokumentasjon, men i mange tilfeller er det bare linjeskiftene som er endret.
Denne innstillingen skal fikse på det.
Mer info:
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

Skru av LF-normalisering på API-dok

---

doc/nve-label.md
src/components/nve-label/nve-label.ts

Siden tooltip-property var initialisert med '', ble den tatt med i DOM selv om den ikke brukes:
Nå har jeg satt tooltip-property valgfri.
Takk til @amish1188 som tipset meg om dette!

Fjernet tooltip-property i nve-label fra DOM hvis den ikke brukes

---

src/components/nve-input/nve-input.ts
src/components/nve-label/nve-label.ts

Fikk denne feilmeldinga da jeg brukte nve-label i Abonner:
```
reactive-element.ts:1394  Uncaught (in promise) Error: The following properties on element nve-label will not trigger updates as expected because they are set using class fields: value, size, light, tooltip. Native class fields and some compiled output will overwrite accessors used for detecting changes. See https://lit.dev/msg/class-field-shadowing for more information.
at NveLabel.performUpdate (reactive-element.ts:1394:17)
```
Prøver å fjerne reflect = true på alle properties for å se om dette hjelper.

Tatt bort reflect = true på alle properties

---

src/components/nve-label/nve-label.styles.ts
src/components/nve-label/nve-label.ts

Fant en feil som gjorde at nve-label med tooltip-slot ikke ble vist. For at dette skulle virke:
```
<nve-label value="Ledetekst">
<div slot="tooltip">Hjelpetekst</div>
</nve-label>
```
måtte vi gi slot'en som inneholdt ledeteksten et (tilfeldig) navn. "Default" slot ble ikke vist.

Viser tekst i nve-label selv om tooltip ligger i slot

---

src/components/nve-dropdown/nve-dropdown.component.ts
src/components/nve-input/nve-input.component.ts
src/components/nve-input/nve-input.demo.ts
src/components/nve-input/nve-input.styles.ts

Man kan enten bruke constraint validering med attributer, eller bruke setCustomValidity for å validere input feltet.
Begge to eksemplarer vises i demo.
Input felt blir bredere når feil ikonen vises. Forklart i koden. Man burde kanskje sette noe bestemt bredde eller noe? 
Gjerne test i varsom appen

PR: AVN-289 basic input validering

---

doc/components.md
doc/nve-alert.md
doc/nve-button.md
doc/nve-checkbox-group.md
doc/nve-checkbox.md
doc/nve-dialog.md
doc/nve-dropdown.md
doc/nve-label.md
doc/nve-menu.md
doc/nve-tooltip.md
src/components/nve-tooltip/nve-tooltip.component.ts

- Har lagt inn linkene som manglet i "menyen" for API-dok. Det er lett å glemme å legge inn linker i fila components.md når vi lager API-dok. Burde nok ha en script som genererte denne fila.
- Har lagt inn link til Shoelace-dok for nve-tooltip
- Har generert API-dok på nytt. Var en del oppdateringer siden sist

Har lagt inn link til alle komponentene vi har i "API-dok-menyen" + litt småfiks i JsDoc + generert API-dok på nytt

---

src/components/nve-radio-group/nve-radio-group.styles.ts

Det var for trangt mellom radioknapper som står under hverandre.
Slik så det ut:
Har oppdatert iht. Figma (og skisser i Abonner).

Riktig mellomrom mellom radioknapper som står under hverandre

---

src/components/nve-radio-group/nve-radio-group.component.ts
src/components/nve-radio-group/nve-radio-group.styles.ts
src/components/nve-radio/nve-radio.demo.ts
src/components/nve-radio/nve-radio.styles.ts
src/utils/updateInvalidProperty.ts

La til kommentarer på properties i radio gruppe.
Tydeligvis har sl-radio-gruppe property som heter errorMessage som ikke er tilgjengelig via super. Hvis jeg sender vår egen errorMessage så overskrives det et sted i formcontroll klasse som gjør at vi får en default melding, ikke det som var ønsket via vår errorMessage. Derfor må jeg bruke state og lagre meldingen som skal brukes senere i setCustomValidity.
Det er kun required attribute som fungerer via constraint validation. Altså hvis man har required, burde man få en feilmelding (se demo).
For å gi alle radio knapper en style mens radiogruppe feiler, toggler jeg data-invalid attribute (ikke data-user-invalid). Både her i checkbox gruppe man trenger ikke å ha data-user-invalid på alle radioer fordi den feiler som helheten. Data …

PR: avn-258 radio validation

---

src/components/nve-checkbox-group/nve-checkbox-group.component.ts
src/components/nve-checkbox-group/nve-checkbox-group.demo.ts
src/components/nve-checkbox-group/nve-checkbox-group.styles.ts
src/components/nve-checkbox/nve-checkbox.component.ts
src/components/nve-checkbox/nve-checkbox.demo.ts
src/components/nve-checkbox/nve-checkbox.styles.ts
src/components/nve-label/nve-label.styles.ts
src/stories/nve-checkbox-group/NveCheckboxGroup.stories.ts
src/stories/nve-checkbox-group/NveCheckboxGroup.ts
src/stories/nve-checkbox-group/NveCheckboxGroupDoc.mdx
src/stories/nve-checkbox/NveCheckbox.stories.ts
src/stories/nve-checkbox/NveCheckbox.ts
src/stories/nve-checkbox/NveCheckboxDoc.mdx
src/utils/updateInvalidProperty.ts

Selv om sjekkboksgruppe er vår egen komponent jeg prøvde å 'etterligne' shoelace validering så at bruker ikke blir forvirret når de ser på komponentene i DOMen. Altså jeg la til samme attributer som shoelace bruker: data-valid, data-invalid, data-user-valid, data-user-invalid. Sjekkobksgruppe kaster også sl-invalid hvis valideringen feiler. 
Både her i checkbox gruppe man trenger ikke å ha data-user-invalid på alle sjekkbokser/radioer fordi den feiler som helheten (gruppe). Data user-invalid vises kun når man har tatt på en element så det gir ikke å toggle den, siden man må ikke ta på alle sjekkbokser for å vise feil. Derfor styles den på data-invalid.
Jeg la til alle UU viktige attributer
Testing akkurat på samme måte som input og radio sjekkboks. Man kan teste required (eneaste …

PR: AVN-291 added checkbox group validation

---

src/components/nve-radio-group/nve-radio-group.component.ts
src/components/nve-radio-group/nve-radio-group.styles.ts
src/components/nve-radio/nve-radio.demo.ts

Ser ut at hvis vi fjerner fnytter  her  i `"${this.requiredLabel}"`
this.style.setProperty('--sl-input-required-content', `"${this.requiredLabel}"`);
html skjønner ikke at this.requiredLabel er en verdi fordi den må ha fnytter der

PR: bugfix vi må beholde fnytter i setProperty

---

doc/nve-label.md
doc/nve-menu-item.md
doc/nve-menu.md
doc/nve-popup.md
src/components/nve-label/nve-label.component.ts
src/components/nve-label/nve-label.demo.ts
src/components/nve-label/nve-label.styles.ts
src/components/nve-menu-item/nve-menu-item.component.ts
src/components/nve-menu-item/nve-menu-item.demo.ts
src/components/nve-menu/nve-menu.component.ts
src/components/nve-menu/nve-menu.styles.ts
src/stories/nve-dropdown/NveDropdown.stories.ts
src/stories/nve-dropdown/NveDropdown.ts
src/stories/nve-label/NveLabel.stories.ts
src/stories/nve-label/NveLabel.ts
src/stories/nve-label/NveLabelDoc.mdx

Per i dag category property på nve-menu-item fungerer ikke som tenkt. Det er menu-item som gjør at kategori er tabbable. Den burde ikke det. Derfor bruker vi nve-label istedenfor. Tooltipen fungerer også på den, fordi det var ikke mulig å legge til tooltipen hvis man brukte nve-menu-item med property category

PR: oppdatert nve-menu-label så at den kan brukes som kategori divideren i nve-menu

---

src/components/nve-radio-group/nve-radio-group.component.ts

resetValidation  i update burde kjøres når både data-invalid og data-user-invalid er borte. ellers så nullstiller errorMessageCopy for tidlig.

PR: AVN-381 resetValidation fikset

---

src/components/nve-popup/nve-popup.component.ts
src/components/nve-select/nve-select.component.ts

Den importerer fra shoelace på den gamle måten som gjør at hele shoelace pakka blir importert. Ikke bra. 
Jeg har også la til as any i sl- eventer fordi etter vi har endret måten vi importerer shoelace komponenter ts skjønte ikke at input kunne ta sl- eventer i metoden vi overksrev.

PR: BUG - set proper import from shoelace in popup

---

src/components/nve-icon/nve-icon.component.ts

Den eksponerer en intern element (span) så at vi kan tilpasse styling i konsumerende applikasjoner når vi trenger det

PR: la til part til ikone

---

README.md
src/components/nve-checkbox/nve-checkbox.styles.ts
src/components/nve-input/nve-input.styles.ts
src/components/nve-option/nve-option.styles.ts
src/components/nve-radio/nve-radio.styles.ts
src/components/nve-select/nve-select.styles.ts

Tydeligvis safari har problemer med å prioritere ```:host(:hover)::part(control)```over klassenavn derfor shoelace sin styling blir overskrevet (som i checkbox, radio, input, select). Kan være at det er flere komponenter som feiler men jeg testet kun de som vi brukte i Abonner appen

PR: bug noen komponenter fungerer ikke som de burde i safari

---

src/components/nve-input/nve-input.component.ts
src/components/nve-input/nve-input.demo.ts

Jeg fjerner alle suffix slots i nve-input hvis input ikke feiler. Det gjøt at vi kan ikke bruke suffix. Derfor endrer legger jeg til en id error-icon på 'feil' ikone og fjerner kun den når validering gikk greit. Du kan teste det i demo. Jeg la til en ekstra ikone i den første demo biten med validering.

PR: avn-355 nve-input suffix slot fikset

---

.storybook/main.ts
doc/nve-icon.md
doc/nve-stepper.md
index.html
src/components/nve-icon/nve-icon.component.ts
src/components/nve-icon/nve-icon.styles.ts
src/registerIcons/systemLibraryCustomization.ts

Per i dag man må importere material symboler i index.html for å få det til å fungere. Endringene i denne PRen gjør at man trenger ikke å tenke på det noe lenger. Den legger til import lenke til document header på den første bruk av nve-icon i DOMen. Den legger til header med riktig material bibliotekk basert på 'library' property (Outlined er default). Den legger til <link> i headeren kun en gang

PR: added programmatic imports of material icons

---

src/components/nve-checkbox-group/nve-checkbox-group.component.ts
src/utils/deepCompare.ts

Nve-checkbox-group bruker selectedValues som returnerer verdier til alle valgte sjekkboksene i gruppa. 
Per i dag, var det ikke mulig å sammenlikne objekter, (hvis man klikker av en sjekkboks updateSelectedValues fikk ikke å sammenlikne ikke primitive typer, derfor ble de ikke slettet fra selectedValues array). Denne løsningen fikser problemet.

PR: nå kan man også sammenlikne objekter i selectedValues i nve-checkbox-group

---

doc/nve-stepper.md
doc/nve-textarea.md
public/css/global.css
src/components/nve-alert/nve-alert.styles.ts
src/components/nve-checkbox/nve-checkbox.styles.ts
src/components/nve-icon/nve-icon.styles.ts
src/components/nve-input/nve-input.styles.ts
src/components/nve-textarea/nve-textarea.component.ts
src/components/nve-textarea/nve-textarea.demo.ts
src/components/nve-textarea/nve-textarea.styles.ts
src/main.ts
src/nve-designsystem.ts
src/stories/nve-input/NveInput.stories.ts
src/stories/nve-textarea/NveTextarea.stories.ts
src/stories/nve-textarea/NveTextarea.ts
src/stories/nve-textarea/NveTextareaDoc.mdx

Tenkte først å arve fra nve-input men, den krevde ekstra unødvendig arbeid med å sette ikone på et riktig sted. Derfor har jeg bestemt å lage en separat komponent. Som result ble det en enkel komponent som kan brukes enda enklere enn vanlig nve-input felt. Jeg tror vi kan gjerne gjøre om nve-input på samme måte i fremtiden. 
Komponent støttes både custom og constratint validering akkurat som vanlig input. 
Hadde noen små problemer med å vise default requiredLabel i storybook. Vet ikke hvorfor det funka ikke fra starten. Jeg satt opp *Obligatorisk i render metode. Jeg testet pakken med en eksternt prosjekt og alt virka som det burde.

PR: lagde textarea komponent

---

doc/nve-select.md
src/components/nve-select/nve-select.component.ts
src/components/nve-select/nve-select.demo.ts
src/components/nve-select/nve-select.styles.ts
src/components/nve-textarea/nve-textarea.demo.ts

Nå får vi riktig styling i nve-select hvis det oppstår et feil. 
Klarte ikke å legge til feil ikone dessverre. Eneste måte å kunne gjøre det på er å bruke ::after pseudo-element på noen av partene fordi både clear-button og expand-icon partene kan ikke utvides, og det finnes ikke noe annet slot jeg kunne bruke. Prøvde å sette en ikone inn i ::after men det funka ikke. Vil si at vi kanskje må ha egen komponent hvis vi mener at ikonen er veldig viktig.

PR: lagt til validering i nve-select

---

src/components/nve-textarea/nve-textarea.component.ts
src/components/nve-textarea/nve-textarea.styles.ts

I første omgang så trodde jeg at det er smart å vise *obligatorisk (eller annen type requiredLabel) selv om man ikke skulle vise vanlig label. Problemet med dette er at hvis i et annet prosjekt jeg hadde lyst til å vise nve-label separat (prosjekts spesifikk oppsette) men fortsatt bruke constraint-validering på textarea, jeg hadde både min separat nve-label og *Obligatorisk label under den (sjekk vedlegg). Det finnes ikke i nve-input for eksempel, så jeg burde faktisk følge samme mønster.
Forresten var det en del problemet med posisjonering av ikone når textarea feiler. Hvis jeg ville ha en bredde på textarea så fulgte ikonen ikke med når man endret størrelsen på textarea. Den ble løst med en ekstra kontainer som vises retter textarea og som inneholder ikone med absolute posisjonering. …

PR: oppdatere textarea label og visning av ikone

---

src/components/nve-select/nve-select.styles.ts

**PR**
- Removed min and max width to support more flexible select component. When having a long Option name the name did not fit inside the select.

Removed min and max width to support more flexible select component

---

doc-site/.vitepress/config.mts

Vi burde fikse slik at vi kan nekte folk å pushe rett til main, siden vi nå åpner for enkel redigering av dok-sidene med "Rediger denne sida i Github". Men da må vi fikse scriptet som publiserer til npm først.

Norske tekster i overskrifter for navigering og sideinnhold + linker til redigering av sider i Github, Figma og NPM

---

doc-site/.vitepress/theme/components/SandboxPreview.vue
doc-site/components/nve-checkbox-group.md

Å vise bruk av `nve-checkbox-group` sin `selectedValues` vha html var ikke så lett. 
Nå har jeg skrevet om kodeeksemplet til Vue, og da virker det fint.

Vue-eksempel for å vise bruk av selectedValues i nve-checkbox-group

---

doc-site/.vitepress/theme/components/CodeExamplePreview.vue
doc-site/components/nve-alert.md

Denne PR løser manglende funksjonalitet på script-tagenes inni kodeeksemplarer. Når man legger til script-tag i CodeExamplePreview ```html kodeblokken, skal scriptet fungere

PR: får script delen i kodeeksempel kjøre

---

doc-site/components/nve-button.md
src/components/nve-button/nve-button.component.ts
src/components/nve-button/nve-button.styles.ts

Endret en del på hvordan vi setter farge på knappene. Bruker nå [variant]-attributten på host istedenfor SL-klassene, det gir bedre muligheter
"Secondary" i dokumentasjonen er tatt bort, det er "default" som skal brukes
Siden vi nå bruker [variant]-selector så har jeg da også lagt til mulighet i css til å bruke <nve-button variant="ghost" /> (samme secondary og outline som variant) siden det er det designsystemet vel bruker.
Merk at vi ikke får overskrevet mulige varianter i shoelace, de er hardkodet som
variant: 'default' | 'primary' | 'success' | 'neutral' | 'warning' | 'danger' | 'text';

Fikser for hover og darkmode på farger

---

doc-site/.vitepress/theme/components/Card.vue
doc-site/.vitepress/theme/components/CodeExamplePreview.vue
doc-site/.vitepress/theme/components/SandboxPreview.vue
doc-site/.vitepress/theme/components/apidoc/ComponentMethods.vue
doc-site/components/nve-alert.md
doc-site/components/nve-dropdown.md
doc-site/components/nve-message-card.md
doc-site/introduction/forDesigner/contribution.md
doc-site/introduction/forDesigner/getStarted.md
doc-site/introduction/forDevelopers/codeExamples/stepper.md
doc-site/introduction/forDevelopers/validation.md
doc-site/introduction/forDevelopers/vue.md
doc-site/introduction/home.md
src/components/nve-alert/nve-alert.component.ts
src/components/nve-message-card/nve-message-card.component.ts
src/components/nve-message-card/nve-message-card.styles.ts

Message-card ligner på alert men det er ikke det samme. message-card skal brukes som en lengre boks med teksten for  å gi brukere ekstra info i skjemaer f.eks. Jeg lagde den fordi vi skal bruke den i ds dokumentasjonen som tips, varsel bokser. 
CodeExamplePreview.vue ble endret til å bruke iife for å kjøre scripter. Grunnen er at når man kjører en script i global scopet lagrer variabler, og når man går til en annen side og kommer tilbake den klager at variabler allerede ble definert. Iife gjør at scopet er lokalt, og den blir ødelagt når vi bytter siden (du kan sjekke problemet i nve-alert f.eks der vi bruker en script for å lukke alerten). 
ComponentMethods begrenser nå visning av private og lit sine lifecycle metoder. Vi trenger ikke å vise dem.
Message-card lukk knappen gjør det …

PR: lagde message--card komponent

---

doc-site/components/nve-button.md
doc-site/components/nve-icon-button.md
scripts/createNewComponent.js
src/components/nve-button/nve-button.component.ts
src/components/nve-button/nve-button.styles.ts
src/components/nve-icon-button/nve-icon-button.component.ts
src/components/nve-icon-button/nve-icon-button.styles.ts
src/interfaces/NveComponent.interface.ts

Ny komponent nve-icon-button. Den arver fra nve-button, men kun viser ikonen. 
Måtte bruke iconName siden name property allerede eksisterer på knappen, og jeg ville ikke overskrive den
Jeg måtte justere selve nve-button litt fordi det var en del endringer som påvirket hvordan icon knapp vises. 
F.eks størrelse på ikonen skal alltid være 24px. Før `small`hadde ikon med 20px. 
Jeg la til transisjon på nve-button også, den burde være 0.3s. Per i dag er det shoelace sin transisjon som varer 0.5ms.

feat(nve-icon-button): Added new component

---

doc-site/components/nve-alert.md
doc-site/components/nve-badge.md
doc-site/components/nve-message-card.md
package.json
src/components/nve-alert/nve-alert.component.ts
src/components/nve-alert/nve-alert.styles.ts
src/components/nve-badge/nve-badge.component.ts
src/components/nve-badge/nve-badge.styles.ts
src/components/nve-message-card/nve-message-card.component.ts
src/components/nve-message-card/nve-message-card.styles.ts

Skrev om:
"low" på nve-badge 
"emphasized" på nve-message-card
"emphasized" på nve-alert
til å bruke "saturation"-attributt istedenfor (med subtle/emphasized). 
Merk at vi også går bort fra "low" og bruker "subtle" istedenfor. Dette er fra Figma

Endre "low" og "emphasized"-attributter. Gjelder nve-badge, nve-message-card og nve-alert

---

doc-site/.vitepress/theme/components/CodeExamplePreview.vue
doc-site/.vitepress/theme/components/ComponentIssues.vue
doc-site/.vitepress/theme/components/ComponentLayout.vue
doc-site/.vitepress/theme/components/ComponentOverview.vue
doc-site/.vitepress/theme/github.services.ts
doc-site/.vitepress/theme/github.store.ts
doc-site/components/Komponentoversikt.md
doc-site/package-lock.json
doc-site/package.json

Vi viser nå alle åpne *issues* fra repoet vårt i komponentoversikten og på sida for hver komponent. Issues er i denne sammenheng både saker og pull requests.
En sak må merkes med komponentnavn for at vi skal vite at saken hører til en bestemt komponent. 
NB! Alle issues merka med komponentnavn blir vist. Det samme gjelder PR'er. PR'er som _ikke_ er merka med komponentnavn, men er koblet til en komponent gjennom en sak, vises ikke. Årsaken er at endepunktet jeg bruker, gir ingen kobling mellom sak og PR. Dette kan vi sikkert få til på sikt, men det krever mer koding.
Her er dokumentasjon på endepunktet jeg bruker:
https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-repository-issues
Jeg har også forenklet koden for å summere antall komponenter og forsøkt å gjøre …

Viser saker i Github merka med komponentnavn i komponentoversikten

---

doc-site/.vitepress/theme/components/apidoc/ComponentFields.vue

Her er et eksempel på at beskrivelses-kolonna blir kutta:
https://designsystem.nve.no/components/nve-button.html#egenskaper
Har gjort noen små-endringer for å gi bedre plass til beskrivelses-kolonna:
- Redusert bredde på attributtsynk-kolonna ved å endre overskrit til "A". Har heller lagt inn en link til hva "A" betyr
- Flytta attributtsynk-kolonna lengst til høyre
- Slått sammen type- og standard-verdi-kolonnene til en kolonne med dette formatet: `<type> = <standardverdi>`
Sånn ser det ut nå:

Gjort bedre plass til beskrivelse i egenskaps-tabell

---

scripts/createNewComponent.js
src/nve-designsystem.ts

Når man kjører `npm run add-component nve-xxxx` så ble ikke den nye komponenten eksportert fra nve-designsystem.ts - listen.
La til kode slik at den legges til der (og sorteres alfabetisk)

La til funksjonalitet for at createNewComponent også legger til komponenten i nve-designsystem

---

doc-site/components/nve-input.md

Vi trengte litt sære dato-valg i SeNorge, og vi var usikre på om `nve-input` kunne brukes. Den viste seg å være mer kapabel enn vi trodde, så jeg har laget flere eksempler på valg av dato/tidspunkt. 
Se under "Datatyper" i dokumentasjonssida.

Har laget flere eksempler på datohåndtering i nve-input

---

src/components/nve-input/nve-input.component.ts

Noen ganger validerer nettleseren selv om det ikke er ønsket som f.eks i dato type. noValidation attribute skal hindre fra validering.

fix(nve-input): hindre validering der hvor det ønskes

---

src/components/nve-radio-group/nve-radio-group.styles.ts

Changed label in `nve-radio-group` to bold to match the other labels in the design system
**Before:**
**After:**

feat: change label to bold

---

doc-site/components/nve-accordion.md
src/components/nve-accordion/nve-accordion.component.ts
src/components/nve-accordion/nve-accordion.styles.ts

Mindre endringer på accordion etter input fra designer
* Ikonstørrelse for chevron er nå 24px
* Tok bort mulighet for å høyrejustere chevron
* Minsket spacing mellom tittel og content

fix: Designer-endringer accordion

---

doc-site/.vitepress/theme/github.services.ts

Nå viser vi link til github-saker også for komponenter som ikke er laget ennå:
Closes #239.

feat(#239): Vise også saker som gjelder planlagte komponenter i komponentoversikten

---

doc-site/components/nve-radio-group.md
doc-site/components/nve-radio.md
src/components/nve-radio/nve-radio.styles.ts

Fixes  #316, fixes #320.
Har også dokumentert bruk av størrelse på `nve-radio` og `nve-radio-group`.
Så vidt jeg kunne se er det allerede riktig størrelse på ikoner/avkrysningsbokser.
`nve-checkbox` skal iflg. vårt designsystem ha en fast størrelse, og dette er dokumentert i JsDoc, se https://designsystem.nve.no/components/nve-checkbox.html

fix(nve-radio): Skriftstørrelse på stor variant av nve-radio

---

doc-site/components/nve-input.md
src/components/nve-input/nve-input.component.ts
src/components/nve-input/nve-input.styles.ts

Finnes også logikk for å legge til/fjerne ikonet dersom readonly endres. Og dersom det er noe i suffix-slot så bruker vi det ikke.

Fixes #227 . nve-input får nå et øye-ikon dersom den er readonly

---

doc-site/components/nve-textarea.md
src/components/nve-label/nve-label.component.ts
src/components/nve-textarea/nve-textarea.component.ts
src/components/nve-textarea/nve-textarea.styles.ts

Filled får nå valideringsborder
Label som er i textarea har nå for-attributt satt. Bruker random id inne i komponenten

Fix #355, #356 : Endringer på textarea.

---

doc-site/components/nve-option.md
doc-site/components/nve-select.md
src/components/nve-option/nve-option.component.ts
src/components/nve-select/nve-select.component.ts

I Kontroll har vi et eksempel hvor nve-option har "bilde - bildenavn - bildetekst", men når den er valgt skal vi kun vise bildetekst i selve select'en. 
Select kaller getTextLabel() -funksjonen på valgte elementer , så vi overskriver getTextLabel på nve-option en og sender med en ekstra attributt på nve-option.
Default er at vi kun kaller super.getTextLabel dersom textLabel ikke er satt.

Fixes #364 Kan nå ha en textlabel-attributt på nve-option

---

src/components/nve-accordion-item/nve-accordion-item.styles.ts

Enkel fiks, bare setter fill på ikonet til currentColor

Fix 363 . Ikonet for å åpne/lukke var alltid sort, selv på darkmode

---

doc-site/.vitepress/theme/components/apidoc/ComponentDescription.vue

Det er lett å glemme at komponentene våre kanskje har flere muligheter enn det vi har valgt å dokumentere selv.
Har derfor lagt inn denne på "komponentsida" for hver komponent som arver fra Shoelace:

docs: Oppfordring om å sjekke Shoelace-dok for komponenter basert på Shoelace

---

doc-site/components/nve-button.md
src/components/nve-button/nve-button.styles.ts

Når man brukte en <nve-button size="small"> med et nve-icon i prefix/suffix -slot så var ikonet 24px høyt. Det skal være 20.
Sjekket også Figma for "large" button. Denne er 24px, akkurat som default

fix: Størrelse på ikon i small nve-button var 24px, ikke 20

---

src/components/nve-button/nve-button.component.ts
vite.config.ts

Fikser et feil etter [denne PRen](https://github.com/NVE/Designsystem/pull/439).
Nå skal vi importere riktig nve-designsystem.css i global.css etter bygging.

fix: rette .css stier i global.css

---

src/components/nve-link-card/nve-link-card.component.ts
src/components/nve-link-card/nve-link-card.styles.ts

- Endret fra border til outline på :hover slik at innholdet ikke forskyver seg på hover.
- Lagt til en blå outline på css :active (pressed) når brukeren klikker på cardet, slik som beskrevet i Figmaskissene.
- Gjort det mulig å tabbe på cardene for bedre tilgjengelighet, lagt til en handleKeyDown funksjon slik tastaturbruker kan klikke på det ved å trykke "Enter" tasten.
fixes #451

fix(nve-link-card): css outline og tab accessibility

---

doc-site/.vitepress/config.mts
doc-site/introduction/designelementer/animasjoner.md
doc-site/introduction/designelementer/avstander.md
doc-site/introduction/designelementer/farger.md
doc-site/introduction/designelementer/tokens.md
doc-site/introduction/designelementer/typography.md
doc-site/introduction/designelementer/visuellform.md
doc-site/introduction/forDesigner/contribution.md
doc-site/introduction/forDesigner/design.md
doc-site/introduction/forDesigner/getStarted.md
doc-site/introduction/forDevelopers/development.md
doc-site/introduction/forDevelopers/vue.md
doc-site/introduction/home.md

Fjernet link til Jira og skrevet tydeligere hvordan man bør gå fram for å melde feil og bidra til endringer.
Har også endret menyvalget fra "Utvikling" til "Les dette først":
Fjernet også denne teksten:
_TODO: Legg til tab komponent_ 
fra en rekke sider, siden vi ble enige om å droppe faner.

docs: Oppdatert introduksjonssida for utviklere

---

doc-site/components/nve-menu-item.md
src/components/nve-divider/nve-divider.component.ts
src/components/nve-menu/nve-menu.styles.ts

Det var en liten feil på nve-menu som gjorde at bakgrunnen til sl-menu lakk igjennom. Kun synlig i darkmode.

fix: Feil farge på nve-divider, og feil på nve-menu i darkmode

---

doc-site/.vitepress/theme/components/TypographyTable.vue
doc-site/.vitepress/theme/cssTokenState.ts
doc-site/.vitepress/theme/index.ts
doc-site/.vitepress/theme/types/FontValues.ts
doc-site/introduction/designelementer/typography.md

Oppdaterte typografi siden som nå viser våre font tokene + font 'grupper' (som headers, subheaders osv). 
Alt verdier hentes direkte fra css filer, de er ikke hardkodet (bortsett fra font-family i TypographyTabel komponent).
Man kan vise hvordan typografi tokene endrer seg basert på skjermstørrelesen. 
Var usikker om jeg skal skrive noe under forskjellige font grupper. Har bare skrevet noe under headers.
Gjerne si fra om dere syns innholdet burde skrives om eller noe.

docs(typography): oppgradert typografi dokumentasjon

---

src/components/nve-carousel/nve-carousel.styles.ts

Knekker i nyere Chromium-baserte browsere
::part::after er ikke en gyldig selector ihht spesifikasjonen

fix: Fikset en selector som var feil på nve-carousel. 

---

doc-site/components/nve-stepper.md
src/components/nve-stepper/nve-step/nve-step.component.ts
src/components/nve-stepper/nve-step/nve-step.styles.ts
src/components/nve-stepper/nve-stepper.component.ts

Denne PRen forbedrer nve-stepper med ny funksjonalitet, fikser en "feil" og oppdaterer dokumentasjon.
* **Ny `hideDescriptions` property**:
- Lagt til `hideDescriptions` i `StepProps` og `NveStep` for å tillate å skjule beskrivelser og en mer kompakt visning. [[1]](diffhunk://#diff-0aecb4bb76df86fc16ecce8403ea132e66a93eda9b58841ceedc254ce2601380L23-R23) [[2]](diffhunk://#diff-0aecb4bb76df86fc16ecce8403ea132e66a93eda9b58841ceedc254ce2601380R74-R77)
- Oppdatert `NveStepper` med `hideDescriptions`. [[1]](diffhunk://#diff-fb644bfa12b5c8bbb1058ae4879db2555acb97b2efddd8f64c8e35a1d4953b3bR22-R24) [[2]](diffhunk://#diff-fb644bfa12b5c8bbb1058ae4879db2555acb97b2efddd8f64c8e35a1d4953b3bR89-R92) [[3]](diffhunk://#diff-fb644bfa12b5c8bbb1058ae4879db2555acb97b2efddd8f64c8e35a1d4953b3bR283)
* **Endret …

fix(stepper): 511 stepper skjuling av description for et steg fungerer ikke

---

custom-elements-manifest.config.js

Kunne ikke bygge med node 22, siden assert-imports ikke lenger er støttet (skal bruke `with` istedenfor)

fix: Kan nå bygge med node 22

---

doc-site/.vitepress/theme/components/ComponentOverview.vue
doc-site/.vitepress/theme/components/apidoc/ComponentDescription.vue
doc-site/components/nve-alert.md
doc-site/components/nve-darkmode-switch.md
doc-site/components/nve-dropdown.md
doc-site/components/nve-icon.md
doc-site/components/nve-link-card.md
doc-site/components/nve-message-card.md
doc-site/components/nve-stepper.md
doc-site/introduction/forDesigner/contribution.md
doc-site/introduction/forDesigner/getStarted.md
doc-site/introduction/forDevelopers/development.md
doc-site/introduction/forDevelopers/validation.md
src/components/nve-alert/nve-alert.component.ts
src/components/nve-alert/nve-alert.styles.ts
src/components/nve-link-card/nve-link-card.component.ts
src/components/nve-link-card/nve-link-card.styles.ts
src/components/nve-message-card/nve-message-card.component.ts
src/components/nve-message-card/nve-message-card.styles.ts
src/components/nve-stepper/nve-step/nve-step.component.ts
src/components/nve-stepper/nve-step/nve-step.styles.ts
src/components/nve-stepper/nve-stepper-mobile.component.ts
src/components/nve-stepper/nve-stepper-mobile.styles.ts
src/components/nve-stepper/nve-stepper.component.ts

BREAKING CHANGES
PR-en løser [problemet 525](https://github.com/NVE/Designsystem/issues/525).
Jeg valgte ikke å fikse selve nve-alert. Det er en del problemer med visning av komponenten, men det skal fikses i en separat PR. 
Jeg bestemte å endre title til label i stepper props. Usikker om det er så viktig, men tenkte bare å bruke samme navn siden selve property i nve-step skal nå hete label, ikke title. Alle komponentne skal virke som før, med en forksjell for å ikke bruke title. Brukere kan bruke title selv om de har lyst til det i deres prosjekter.
Nå skal vi ikke ha tooltips når man hover over nevnte komponenter. Bruk av title som property navn burde bli forbudt, tenker jeg.

feat(mange komponenter)!: fjern titel property i nve-alert, nve-stepper, nve-message-card, nve-link-card

---

src/components/nve-alert/nve-alert.component.ts

for å publisere riktig versjon 2.0.1 siden 2.0.0 vil ikke bli publisert. Det er en del caching som gjør at vi ikke kan ha versjon 2.0.0.

fix(nve-alert): fikse kommentar

---

src/components/nve-label/nve-label.styles.ts

Vi har hatt problemer med at tooltippen ikke kommer frem der den skal i flere tilfeller. (laaangt unna)
Dette gjelder nve-label og nve-tooltip.
Denne PR fikser nve-label men ikke nve-tooltip da nve-tooltip ikke er wrappet i et element.

fix(nve-label): posisjoneringen av tooltip var feil

---

.github/workflows/build-and-deploy-doc-site.yml
.github/workflows/publish-npm.yml
README.md
eslint.config.js
package-lock.json
package.json
scripts/createNewComponent.js
src/components/nve-badge/nve-badge.test.ts
src/components/nve-button/nve-button.test.ts
vite.config.ts

Denne PR-en innfører bruk av Vitest, Happy DOM og open-wc/testing for å teste webkomponenter.
Alle nye komponenter bør ha tilhørende tester. Vi kan legge til tester for eksisterende komponenter etter hvert.
Foreløpig har jeg skrevet tester for kun nve-button og nve-badge, slik at andre kan bruke disse som inspirasjon for egne tester.
Det er enkelt å skrive tester for webkomponenter, og alt er beskrevet i README.
Jeg har også lagt til testing i pipeline-scriptet.

fix(test): lagt til test rammeverk

---

doc-site/components/nve-select.md
src/components/nve-option/nve-option.component.ts
src/components/nve-option/nve-option.styles.ts
src/components/nve-select/nve-select.component.ts

Designet i Figma har checkmark på valgte elementer i nve-select. Denne var eksplisitt satt som display: none i vår kode
Jeg tok bort den eksplisitte display: none-koden og erstattet den med en `hide-checkmark" istedenfor. Denne er default `false`

feat(nve-select): Legg inn checkmark på valgte options i nve-select

---

src/components/nve-input/nve-input.styles.ts
src/components/nve-select/nve-select.styles.ts

fix: Endret plassering på *obligatorisk label på nve-select slik den er samme som i nve-input.
Etter endringer:
Issue #613

fix(nve-select): Endret plassering på *obligatorisk label på nve-select

---

doc-site/components/nve-switch.md
src/components/nve-switch/nve-switch.component.ts
src/components/nve-switch/nve-switch.styles.ts
src/components/nve-switch/nve-switch.test.ts

I denne pull requesten har jeg fjernet muligheten for at man kan sette farger selv og lagt til muligheten for å endre siden label er på. Cssproperty har blitt byttet ut med varianter hvor "default"  er lik som den var før og primary (blå,ny) har blitt lagt til. De som har valgt å bruke css property som har blitt fjernet kommer til å få "default color". Muligheten for å sette farger ble fjernet for å hindre variasjoner i bruken av nve-switch.
Hvis vi eventuelt skal utvide denne kan man lett legge til en ny farge ved å legge til litt css og en ny "variant".
**Label** går det nå ann å endre hvilken side den er på ved hjelp av label-position="start || end" hvor end er default (som før)

feat(nve-switch): legge til primary color og label-position
