- tokens/$metadata.json
- tokens/Theme/nve_dark.json
- tokens/Theme/nve_light.json
- tokens/Theme/varsom_dark.json
- tokens/Theme/varsom_light.json
- tokens/private.json
private
11
red.950
Value
#810505
#6B0000
red.999
Value
#730000
#540000
yellow.100
Value
#FFF4D2
#FFF4D1
yellow.950
Value
#ab8207
#795A00
yellow.999
Value
#a27900
#523D00
blue.950
Value
#02345a
#0F3970
blue.999
Value
#00233d
#0B2951
green.100
Value
#E5FCE5
#E8FCE8
green.950
Value
#105427
#004126
green.999
Value
#06421a
#00301C
varsom_brand.000
Value
#fdd0a2
#ffdfba
Theme/nve_light
11
Neutrals.Border.Disabled
Value
{grey.600}
{grey.500}
Interactive.Outlined.Border.Focus
Value
{blue.600}
{blue.500}
Interactive.Links.Focus
Value
{blue.500}
{blue.700}
Feedback.Foreground.Subtle.Info
Value
{grey.800}
{grey.950}
Feedback.Foreground.Subtle.Error
Value
{grey.800}
{grey.950}
Feedback.Foreground.Subtle.Warning
Value
{grey.800}
{grey.950}
Feedback.Foreground.Subtle.Success
Value
{grey.800}
{grey.950} …
> Private fargejustering

- build/css/nve.css
- build/css/nve_dark.css
- build/css/varsom.css
- build/css/varsom_dark.css
- dist/index.html
- index.html
- transform.js
lagt til manglende script som fikset problem med 0-verdier
> PR - fikset problem med zeroes

- README.md
- package-lock.json
- package.json
oppdatert dokumentasjon. Må oppdateres en gang til når alt er på plass.
> PR - oppdatere readme

- build/css/nve.css
- build/css/nve_dark.css
- build/css/varsom.css
- build/css/varsom_dark.css
- src/styles/global.css
- tokens/Theme/nve_dark.json
- tokens/Theme/nve_light.json
- tokens/Theme/varsom_dark.json
- tokens/Theme/varsom_light.json
- tokens/public/device/base.json
Nå er en del shoelace tokene mappet til nve tokene. Vi bestemte å starte med de som vi trodde er enklest og kan mappes 1:1 til de tokene som allerede eksisterer i NVE design system. Det vil bety at man ikke må bry seg om border radius, focus eller størrelse på input, knapper, og selec.t Det var ganske mange input tokene som ble mappet. Input trenger fortsatt en individuel styling men det er en god del som kan hentes fra tokene nå istedenfor. Sizing tokene ble oppdatert
> PR: AVN-213 map sl tokens to ds tokens

- tokens/Theme/nve_dark.json
- tokens/Theme/nve_light.json
- tokens/Theme/varsom_dark.json
- tokens/Theme/varsom_light.json
Add public neutral feedback color tokens for all themes
> Neutral colors

- src/stories/NveButton.stories.ts
- src/stories/NveInput.stories.ts
- src/stories/NveLabel.stories.ts
Linkene i Storybook til api-doc i Github var feil
> Rettet linker til apidok i Github

- src/styles/imports.css
> Oppdaterte fonter

- tokens/public/device/base.json
La til opacity token som er 38% på disabled komponenter
> La til opacity token

- .github/workflows/azure-static-web-app-kind-mushroom-03c272603.yml
- doc/components.md
- doc/nve-checkbox-group.md
- doc/nve-checkbox.md
- doc/nve-radio-button.md
- src/components/index.ts
- src/components/nve-checkbox-group/nve-checkbox-group-demo.ts
- src/components/nve-checkbox-group/nve-checkbox-group.styles.ts
- src/components/nve-checkbox-group/nve-checkbox-group.ts
- src/components/nve-checkbox/nve-checkbox-demo.ts
- src/components/nve-checkbox/nve-checkbox.styles.ts
- src/components/nve-checkbox/nve-checkbox.ts
- src/components/nve-label/nve-label.ts
- src/components/nve-tooltip/nve-tooltip.ts
- src/main.ts
- src/stories/NveCheckbox.stories.ts
- src/stories/NveCheckbox.ts
- src/stories/NveCheckboxGroup.stories.ts
- src/stories/NveCheckboxGroup.ts
Det er en sjekkboks med sjekkboksgruppe og validering med invalid property. Det var eneste måte å gjøre det så at det fungerer med bolske verdier.
> PR: avn 234 sjekkboksgruppe

- src/components/nve-alert/nve-alert.demo.ts
- src/components/nve-divider/nve-divider.component.ts
- src/index.ts
Vi mangler å eksportere nve-divider så at det kan brukes
> PR: exposed divider

- customtransforms/boxShadow.js
Knut bruker et array med skygger i PR 105: https://github.com/NVE/Designsystem/pull/105
Transformeren jeg skrev støtter ikke det, så skrev den om
Vil virke som før på skygger som ikke er et array
> La til mulighet for å kunne ta imot flere skygger, 

- tokens/$themes.json
- tokens/public/device/base.json
Endret
- Font size fra px til rem
- Rettet opp feil i font font-family
- Endret font-weight navn fra 1 og 0 til regular og semibold.
> Endret font-size token fra px til rem

- build/css/nve.css
- build/css/nve_dark.css
- build/css/varsom.css
- build/css/varsom_dark.css
- customtransforms/fixZeroes.js
- customtransforms/fontFamilies.js
- customtransforms/fontSizes.js
- customtransforms/fontWeights.js
- src/main.ts
- transform.js
> PR: bug fontweights transform ikke kjører

- README.md
- doc/nve-badge.md
- package.json
- scripts/createNewComponent.js
- src/components/nve-badge/nve-badge.component.ts
- src/components/nve-badge/nve-badge.demo.ts
- src/components/nve-badge/nve-badge.styles.ts
- src/components/nve-button/nve-button.styles.ts
- src/index.ts
- src/main.ts
- src/stories/nve-badge/NveBadge.stories.ts
- src/stories/nve-badge/NveBadge.ts
- src/stories/nve-badge/NveBadgeDoc.mdx
I tillegg til badge komponenten har jeg lagd en script som oppretter mappe struktur med filene klare til utvikling for deg :)
> PR: AVN-282 nve- badge component

- src/components/nve-radio-group/nve-radio-group.component.ts
Det er en løsning til [Issue 114](https://github.com/NVE/Designsystem/issues/114)
> PR: Issue-114 nullstille errorMessageCopy i radio gruppe

- README.md
Nå som Abonner-prosjektet er ferdig med sitt bidrag til designsystemet, synes jeg det er viktig at vi forsøker å formalisere det vi har etablert som arbeidspraksis etter en del prøving og feiling.
Jeg har fjernet noe unødvendig tekst og formatering, forsøkt å forenkle tekst og lagt til mer der jeg mente det trengtes. Har også byttet litt om på kapitler for å få det jeg mener er viktigst øverst.
Har også forsøkt å skrive noe om hvordan vi "tolker" Figma-designet. Dette er et vanskelig tema, og jeg trenger innspill og kommentarer særlig på dette.
> AVN-285: Forenkling av Readme

- README.md
> PR - endret på SB dokumentasjon

- src/components/nve-button/nve-button.styles.ts
- src/components/nve-icon/nve-icon.component.ts
- src/components/nve-icon/nve-icon.styles.ts
Nve-ikon var for liten. Den ble nå 24px som default og 20px når knappen 'size' er 'small'
> PR: avn-302 forstørret ikon i nve-knapp

- src/components/nve-popup/nve-popup.component.ts
- src/index.ts
Siden det er mer som utility komponent (samme som spinner og divider) bruker jeg ikke tid på demo. Den er veldig bra dokumentert på sl sin side.
> PR: AVN-354 la til nve-popup

- tokens/public/device/base.json
> border-radius-50%-to-50px

- src/components/nve-button/nve-button.demo.ts
- src/components/nve-button/nve-button.styles.ts
- src/components/nve-select/nve-select.component.ts
Det var noe galt med avstander i knappen når man hadde både suffix ikone og loading spinner. Denne løsningen burde fikse problemet
> PR: bug fikse slots bredde i knappen

- doc/nve-alert.md
- doc/nve-badge.md
- doc/nve-button.md
- doc/nve-checkbox.md
- doc/nve-dialog.md
- doc/nve-divider.md
- doc/nve-dropdown.md
- doc/nve-input.md
- doc/nve-menu-item.md
- doc/nve-menu.md
- doc/nve-option.md
- doc/nve-popup.md
- doc/nve-radio-button.md
- doc/nve-radio-group.md
- doc/nve-radio.md
- doc/nve-select.md
- doc/nve-spinner.md
- doc/nve-tooltip.md
- public/css/nve.css
- public/css/nve_dark.css
- public/css/varsom.css
- public/css/varsom_dark.css
- src/components/nve-badge/nve-badge.component.ts
- src/components/nve-badge/nve-badge.demo.ts
- src/components/nve-badge/nve-badge.styles.ts
- src/stories/nve-badge/NveBadge.stories.ts
- src/stories/nve-badge/NveBadge.ts
- src/stories/nve-badge/NveBadgeDoc.mdx
- tsconfig.json
Nå har vi trimmet line-height så at den ligner figma litt mer. Jeg brukte vår egen badge istedenfor shoelace siden det er en ganske enkel komponent, og var enklere å style på vår egen måte.
> PR: badge oppdatert

- src/components/nve-radio-group/nve-radio-group.component.ts
- src/components/nve-select/nve-select.component.ts
Tydeligvis det er noen ts kommentarer som ikke fungerer lenger. Bytter de fleste til ts-ignore
> build bug fixed

- package-lock.json
- package.json
- src/components/nve-stepper/nve-step/nve-step.component.ts
- src/components/nve-stepper/nve-step/nve-step.styles.ts
- src/components/nve-stepper/nve-stepper.component.ts
- src/components/nve-stepper/nve-stepper.demo.ts
- src/components/nve-stepper/nve-stepper.styles.ts
- src/stories/nve-stepper/NveStepper.stories.ts
- src/stories/nve-stepper/NveStepper.ts
If I use value of number, I need på dispatch change event, not necessary with object
> Update selected step index to object to achieve ref-binding

- src/components/nve-textarea/nve-textarea.component.ts
Man trenger noen ganger å style textarea input felt inn i nve-textarea.
> PR: la til 'part' på textarea

- README.md
Added small text section regarding ESLint rules.
> Added small text section regarding ESLint rules

- src/components/nve-textarea/nve-textarea.component.ts
- src/components/nve-textarea/nve-textarea.demo.ts
- src/stories/nve-textarea/NveTextarea.stories.ts
- src/stories/nve-textarea/NveTextarea.ts
rows er en attributt på <textarea>, men <nve-textarea> manglet den. Så jeg la den til
> La til "rows" som en property på nve-textarea

- src/components/nve-menu-item/nve-menu-item.styles.ts
- src/components/nve-radio-group/nve-radio-group.styles.ts
- src/registerIcons/systemLibraryCustomization.ts
Endret to farger i radio-group som ikke eksisterte, samme i nve-menu-item. Satt dem til primary, som er det som er i Figma
ikonet chevron-right hadde hardkodet varsom-farge, satt til currentColor
> Fikset: Det var brukt en fargekode som ikke eksisterte, og et ikon hadde hardkodet varsom-fill

- README.md
- package-lock.json
- package.json
- scripts/createNewComponent.js
- src/components/nve-button/nve-button.component.ts
- src/components/nve-dropdown/nve-dropdown.component.ts
- src/components/nve-input/nve-input.component.ts
- src/components/nve-input/nve-input.demo.ts
- src/components/nve-textarea/nve-textarea.component.ts
- src/interfaces/NveComponent.interface.ts
- src/main.ts
- tsconfig.json
- vite.config.ts
**PR contains:** 
* Created an interface that contains common functionality to be used by all components. The first property in the new Interface is a testId that can be used to find the component when doing tests.
* Have run npm audit fix to fix warnings regarding packages vulnerabilities. 
* Fixed the input demo file by adding a unique ID to every input component and added an inputId prop to nve-input so we avoid console.log warnings.
* Created alias for Interface so it's easier to import INveInterface.
> Adding new common Interface INveComponent, run npm audit fix, added testId, solve console.log warnings

- src/components/nve-radio-button/nve-radio-button.component.ts
- src/components/nve-radio-group/nve-radio-group.component.ts
**PR**
- Added testId to radio buttons to facililate Playwright tests
> Added testTo to radio buttons to facililate Playwright tests

- src/components/nve-stepper/nve-step/nve-step.component.ts
- src/components/nve-stepper/nve-step/nve-step.styles.ts
- src/components/nve-stepper/nve-stepper.component.ts
- src/components/nve-stepper/nve-stepper.styles.ts
**PR**
- Fixed small UI bug which was that the line did not go to the end of next step
- Change interface to avoid ts error in Vue apps.
> feature(stepper):Fixed small UI bug and change interface

- src/components/nve-button/nve-button.styles.ts
PR: 
- Change the CSS according to the design https://www.figma.com/design/0eXhyUrUF7fWi1VaphfpEu/04---%E2%9D%96-Komponenter?node-id=307-14026&m=dev
> feature(nve-button):Fixed CSS according to the design

- doc-site/components/nve-button.md
- src/components/nve-button/nve-button.styles.ts
> NveButton hadde fått en min-width i css. Det blir feil, vi har knapper som kun har et ikon

- doc-site/introduction/forDevelopers/development.md
> Lagt inn linker igjen i utvikler-intro

- doc-site/components/nve-select.md
Laget et par kodeeksempler på hvordan man setter verdien i en `nve-select`.
> Laget eksempler på setting av verdier i `nve-select`, samt flervalg

- doc-site/.vitepress/theme/components/CodeExamplePreview.vue
- doc-site/components/nve-tooltip.md
- src/components/nve-tooltip/nve-tooltip.component.ts
- src/components/nve-tooltip/nve-tooltip.styles.ts
La til de samme variantene og saturation som vi bruker andre steder.
Fikset samtidig også verdiene for padding, font etc slik at disse er som i Designsystemet
La til en del flere eksempler i md-filen også for å gjøre et par ting klarere
> Tooltip er nå stylet med nve-farger (variant og saturation)

- doc-site/.vitepress/theme/components/CodeExamplePreview.vue
> Laget litt bedre dokumentasjon for de nye flex/grid-relaterte props'ene på CodeExamplePreview

- doc-site/.vitepress/theme/components/CodeExamplePreview.vue
- doc-site/.vitepress/theme/components/ComponentIssues.vue
- doc-site/components/Komponentoversikt.md
- doc-site/components/nve-icon.md
- doc-site/components/nve-link-card.md
- package-lock.json
- src/components/nve-link-card/nve-link-card.component.ts
- src/components/nve-link-card/nve-link-card.styles.ts
**PR:** 
- Created new card-link component from the design https://www.figma.com/design/0eXhyUrUF7fWi1VaphfpEu/04---%E2%9D%96-Komponenter?m=dev 
- Fixed correct css to make icons bigger at components/nve-icon.html 
- Make props optionals at CodeExamplePreview to remove all console.logs warnings. 
- Removed import of defineProps since it is unnecessary
> feature(nve-link-card): Created new component

- doc-site/components/nve-link-card.md
- src/components/nve-link-card/nve-link-card.component.ts
- src/components/nve-link-card/nve-link-card.styles.ts
PR: 
Updated nve-link-card with: 
- Uses parts before to facilitate css changes
- Change to using BEM convention 
- Using nothing instead of null in return state 
- Fixed and improved documentation
> feature(nve-link-card): Updated with small fixes

- src/components/nve-alert/nve-alert.component.ts
> feat: testar

- src/components/nve-alert/nve-alert.component.ts
BREAKING CHANGE: everything
fix #42
> feat: testing breaking change with Commitizien

- doc-site/components/nve-relative-time.md
- src/components/nve-relative-time/nve-relative-time.component.ts
- src/components/nve-relative-time/nve-relative-time.styles.ts
- src/components/nve-select/nve-select.component.ts
- src/nve-designsystem.ts
Lager en ny komponent: nve-relative-time. Denne arver fra SlRelativeTime
closes #300
> feat: Ny komponent: nve-relative-time

- package-lock.json
Fikser denne sikkerhets-advarselen:
https://github.com/NVE/Designsystem/security/dependabot/21
> Oppgradert rollup

- doc-site/components/nve-accordion.md
- package-lock.json
- package.json
- src/components/nve-accordion/nve-accordion.component.ts
- src/components/nve-accordion/nve-accordion.styles.ts
En del attributter for å gjøre Accordion mer lik DS
> fix 306: Kan nå sette varianter etc

- src/components/nve-accordion-item/nve-accordion-item.component.ts
fixes #317 
Har testet at compact funker i Vue nå.
> reflect = true på border og compact på nve-accordion-item

- .vscode/settings.json
- src/components/nve-alert/nve-alert.component.ts
> feat(test): :art: commit vs source controll

- src/components/nve-alert/nve-alert.component.ts
beabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabeabea
alert
> feat: beabeabeabeabeabeabeabea

- src/components/nve-alert/nve-alert.component.ts
> feat: testar npx c

- src/nve-designsystem.ts
NveMessageCard og NveLinkCard var ikke eksportert fra nve-designsystem.ts Så la dem til der
> fix: Fixes #334 . La til message/link-card for export

- src/components/nve-select/nve-select.component.ts
Dersom man valgte en option med mus ble aldri `valueHasChanged` satt, så event hadde da forrige verdi satt
> Fixes issue 366 .

- doc-site/.vitepress/theme/components/ThemeSelect.vue
- doc-site/.vitepress/theme/composables/useCurrentTheme.ts
Vi lagrer valgt tema i localstorage når changeCurrentTheme kalles. 
Vi henter det opp fra LS i ThemeSelect.vue og setter tema i onBeforeMount
> Fixes 228 . Lagrer nå valgt tema i localstorage

- doc-site/components/nve-radio-button.md
- src/components/nve-radio-button/nve-radio-button.component.ts
- src/components/nve-radio-button/nve-radio-button.styles.ts
Styler nå nve-radio-button slik det er i de (uferdige) skissene. Skal være nokså enkelt dersom man ønsker flere varianter etc.
> Fixes #352 . Styling av nve-radio-button

- src/components/nve-textarea/nve-textarea.component.ts
Fiks for https://github.com/NVE/Designsystem/issues/218
> Fixed issue 218 - add min height for textarea

- src/components/nve-menu-item/nve-menu-item.component.ts
> feat(test): kort beskrivning

- src/components/nve-popup/nve-popup.component.ts
nej skal ikke med
BREAKING CHANGE: Breaking bad
> feat(docs): titel håper jeg

- src/components/nve-menu-item/nve-menu-item.component.ts
- src/components/nve-popup/nve-popup.component.ts
- src/components/nve-select/nve-select.component.ts
- src/components/nve-skeleton/nve-skeleton.component.ts
> feat(test): hej

- src/components/nve-spinner/nve-spinner.component.ts
- src/components/nve-stepper/nve-stepper.component.ts
> feat(manual scope): test 0

- src/components/nve-accordion/nve-accordion.component.ts
BREAKING CHANGE: everythiung nooooo
> feat: test breaking change 2

- doc-site/components/Komponentoversikt.md
- doc-site/components/nve-drawer.md
- src/components/nve-drawer/nve-drawer.component.ts
- src/components/nve-drawer/nve-drawer.styles.ts
- src/nve-designsystem.ts
Har lagt til nve-drawer i DS, og stylet det lille som kan styles.
> feat(nve-drawer): legge til drawer fra shoelace

- README.md
- design-beslutninger.md
Jeg har savnet et felles sted der vi kan skrive ned hvilke valg vi tar underveis i dette prosjektet.
Her er et forsøk på å dokumentere dette i en markdown-fil.
Som dere ser er den ikke ferdig, men jeg har skrevet om de beslutningene vi har tatt nylig.
Kom gjerne med innspill! 
Godkjenn hvis du synes det er en god ide.
> docs: Starta på design rasjonale

- doc-site/.vitepress/theme/components/ComponentIssues.vue
- doc-site/components/Komponentoversikt.md
- src/components/nve-menu-item/nve-menu-item.styles.ts
- src/components/nve-option/nve-option.styles.ts
Fix #472
Vi fikk fel farge for ikoner og nve-option i mørk modus 
Fiksade også doks highlight farge for.
> fix(472): rettet farge feil på nve-option, nve-ikon i mørk modus

- .github/dependabot.yml
> chore(dependabot): Tester ny dependabot config

- doc-site/components/nve-button.md
- src/components/nve-button/nve-button.component.ts
- src/components/nve-button/nve-button.styles.ts
Gjelder sak #488 . Når man hadde en knapp med kun et ikon så ble knappen tom når man togglet loading
> fix: Når man togglet loading på en knapp så forsvant ikonet

- src/components/nve-textarea/nve-textarea.component.ts
Gjør nå en null-sjekk på om label eksisterer på textarea, ga feilmelding i konsollen
> fix(nve-textarea): Null-sjekk på resizeobserver

- doc-site/components/nve-dialog.md
- src/components/nve-dialog/nve-dialog-styles.ts
- src/components/nve-dialog/nve-dialog.component.ts
Fikset icon-egenskapen, den virket ikke
La til bedre dokumentasjon av ikoner og spor for nve-dialog
> fix(nve-dialog): Fikset ikon-visning ved label, la til mer dokumentasjon

- .vscode/launch.json
- doc-site/.vitepress/theme/style.css
- doc-site/components/nve-tab-group.md
- doc-site/components/nve-tab-panel.md
- doc-site/components/nve-tab.md
- src/components/nve-tab-group/nve-tab-group.component.ts
- src/components/nve-tab-group/nve-tab-group.styles.ts
- src/components/nve-tab-group/nve-tab-group.test.ts
- src/components/nve-tab-panel/nve-tab-panel.component.ts
- src/components/nve-tab-panel/nve-tab-panel.styles.ts
- src/components/nve-tab-panel/nve-tab-panel.test.ts
- src/components/nve-tab/nve-tab.component.ts
- src/components/nve-tab/nve-tab.styles.ts
- src/components/nve-tab/nve-tab.test.ts
- src/nve-designsystem.ts
Test gjerne på mobil og.
Skal legge til vue eksempel når den er i main. Jeg må oppdatere ds versjon i sandboxen.
Er usikker om endring i fontvekt har en positiv effekt på faner. Når vekten i fanen endres ved aktivering, kan det oppleves som om noe er visuell ustabilt – dette skyldes teksten som sprer seg npr vekten endres. Kanksje vi kan ha mindre vekt forskjell mellom aktive/inaktive faner?
> feat(nve-tab-group): add nve-tab, nve-tab-group and nve-tab-panel

- doc-site/components/nve-drawer.md
- src/components/nve-drawer/nve-drawer.component.ts
- src/components/nve-drawer/nve-drawer.styles.ts
- src/components/nve-drawer/nve-drawer.test.ts
I denne PR'en har jeg fjernet X lukke ikonet til fordel for _panel_close. Ikonet bytter seg ut basert på hvilken placement skuffen har.
#471 
#470
> feat(nve-drawer): legge til ikon basert på plassering

- doc-site/components/nve-switch.md
- src/components/nve-dialog/nve-dialog-styles.ts
- src/components/nve-drawer/nve-drawer.styles.ts
- src/components/nve-switch/nve-switch.styles.ts
nve-switch: Ikoner ble ikke vist
nve-drawer: Lukk-ikonet hadde feil farge
nve-dialog: Hvit bakgrunn, og sort lukkeknapp
> fix(darkmode): Problemer med darkmode
